[tool.taskipy.tasks]
baixar = { cmd = "python main.py", help = "Baixa processo." }
exe = { cmd = "pyinstaller main.py --onefile -n baixar_processo_sei.exe", help = "Cria/Atualiza executável para Power Automate." }
